version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: leadcode_database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=leadcode
      - POSTGRES_PASSWORD=leadcode
      - POSTGRES_DB=leadcode_site_db
    volumes:
      - pgdata:/data/postgres
    networks:
      - compose-bridge

  app:
    build: .
    container_name: leadcode_site
    restart: always
    ports: 
      - 3000:3000
      - 9229:9229
    volumes: 
      - .:/usr/app
    networks:
      - compose-bridge
    depends_on:
      - postgresdb

volumes:
  pgdata:
    driver: local

networks:
  compose-bridge:
    driver: bridge
